Alzbetapokorna/be 265 admin panel for oai pmh
oarepo/oarepo-oaipmh-harvester pull request #75
Opened 2024-07-11 13:04 UTC by Alzpeta

2024-07-15 12:42 UTC, mesemus requested changes

2024-07-15 12:42 UTC, mesemus commented on oarepo_oaipmh_harvester/harvester.py
> +            harvester = harvesters[0]
In which case "data" is not available?

2024-07-15 12:42 UTC, mesemus commented on oarepo_oaipmh_harvester/oai_record/services/records/schema.py
Isn't this auto generated?

2024-07-15 12:42 UTC, mesemus commented on oarepo_oaipmh_harvester/ext.py
> +        app.config.setdefault("OAI_RUN_SORT_OPTIONS", {}).update(
Should be the other way round, that is

```
app.config["OAI_RUN_SORT_OPTIONS"] = {
    **config.OAI_RUN_SORT_OPTIONS,
    **app.config.get("OAI_RUN_SORT_OPTIONS", {})
}
```

So that invenio.cfg changes are not overwritten

2024-07-16 14:01 UTC, mirekys approved these changes

2024-07-16 14:07 UTC, merged