harvest button ui
oarepo/oarepo-oaipmh-harvester pull request #76
Opened 2024-07-18 08:27 UTC by Alzpeta

2024-07-18 15:17 UTC, mirekys requested changes

2024-07-18 15:17 UTC, mirekys commented on oarepo_oaipmh_harvester/resources/records/resource.py
>      def execute(self, *args, **kwargs):
missing any kind of security here (anyone can call this as many times as they want, flooding celery with harvest tasks). There must be an Admin action permission guard to call this endpoiint: https://inveniordm.docs.cern.ch/develop/topics/administration_panel/#admin-actions-permissions

2024-07-31 08:51 UTC, mesemus approved these changes

2024-07-31 09:36 UTC, mirekys approved these changes

2024-07-31 09:36 UTC, merged